[tool.black]
line-length = 127
target-version = ["py310", "py311", "py312"]
exclude = '\.git|__pycache__|\.venv|venv|\.pytest_cache|build|dist'
preview = true

[tool.pytest.ini_options]
addopts = "-v --tb=short"
pythonpath = "."
testpaths = ["."]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]

[tool.coverage.run]
include = [
    "backend/main.py",
]
omit = [
    "backend/test_*.py",
    "backend/intelligent_ai.py",
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:"
]
omit = [
    "backend/test_*.py",
    "backend/intelligent_ai.py",
]
